### ISSUE TITLE
Save path issue

### ISSUE THREAD

**Issue by dizzie131** [begleysm/ipwatch#5]
Hi,
Getting this error when running the test script;
```
Current IP differs from old IP.
Successfully sent email
Traceback (most recent call last):
  File "/opt/ipwatch/ipwatch.py", line 288, in <module>
    updateoldip(config.save_ip_path,  currip)
  File "/opt/ipwatch/ipwatch.py", line 207, in updateoldip
    savefile = open(filepath, "w")
IsADirectoryError: [Errno 21] Is a directory: '/home/pi/'
```

Email still sends, so not sure what this means?

**Comment by dizzie131** [comment]
Figured it out. Typo in the config file made by me. Thanks!
