### ISSUE TITLE
how to skip updating servers.json right after cloning

### ISSUE THREAD

**Issue by wushuzh** [begleysm/ipwatch#9]
My github access is not stable. 
Sometimes, the download speed is quite slow. But more ofter, the download cannot be done due to network issue. If I tried many times and luck enough, the download will be successful.

So if remote version cannot be fetched, and also there is a server.json available locally, Is it possible to config the program not to fetch the remote version ?

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ipwatch.py", line 281, in <module>
    currip = getip(int(config.try_count), config.ip_blacklist)
  File "ipwatch.py", line 162, in getip
    currip = ipgetter.myip()
  File "/opt/ipwatch/ipgetter.py", line 54, in myip
    return IPgetter().get_externalip()
  File "/opt/ipwatch/ipgetter.py", line 96, in __init__
    operUrl = urllib.urlopen("https://raw.githubusercontent.com/begleysm/ipwatch/master/servers.json")
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain

{
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by begleysm** [comment]
I suppose you could comment out/delete lines [78 ](https://github.com/begleysm/ipwatch/blob/42ae4323f8208b66ce2d2b2bd1305fd67d76d5da/ipgetter.py#L78) to [103 ](https://github.com/begleysm/ipwatch/blob/42ae4323f8208b66ce2d2b2bd1305fd67d76d5da/ipgetter.py#L103) of [ipgetter.py](https://github.com/begleysm/ipwatch/blob/master/ipgetter.py) which would stop the software from ever updating [servers.json](https://github.com/begleysm/ipwatch/blob/master/servers.json).

However I don't really see how this software is useful at all in an environment with an unstable internet connection as it has to go out and query the "what is my ip" webpage and send email to be useful.  So I'm not included to build in a feature to disable this update via config at this time.
